import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // Remove these imports
import "./globals.css";
import Navbar from "@/components/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { cookies } from "next/headers";
import { ThemeProvider } from "@/components/provider/ThemeProvider";

// Remove Geist font definitions
/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="km" suppressHydrationWarning>
      {/* Change lang to "km" for Khmer */}
      <body
        // Remove Geist font variables from className
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`antialiased`} // Keep antialiased if desired
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-full pt-[100px]">
            <div className="">
              <Navbar />
            </div>
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
